name: pagapetodo
description: PagaPE.


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core:
  firebase_auth: 
  cloud_firestore:
  firebase_storage: ^11.0.4
  google_fonts:
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.9
  local_auth: 
  im_stepper: ^1.0.1+1
  
  firebase_core_platform_interface:
  animations: ^2.0.3

  http: any
  firebase_performance: ^0.9.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  image_path: "assets/VotaPe_logo.png"
flutter:
  uses-material-design: true
  
  assets:
     - assets/